language: node_js
sudo: false
node_js:
  - "7.10.0"

install:
  - npm install

before_script: chmod 0777 ./node_modules/.bin/mocha 

script:
  - npm test

notifications:
  email:
    recipients:
      - mcvarona.cv@gmail.com
      - mcvarona@up.edu.ph
      - huchiu@up.edu.ph
      - kamarinduque@up.edu.ph
    on_success: always # default: change
    on_failure: always # default: always